site_name: ARROW CMS PROJECT
pages:

- [index.md]
- [folder.md, Folder structure]
- [makeFeature.md,Make a feature, Make a feature]
- [session.md,Session]
- [guidelines.md,Guideline]
- [template/custom_filter.md,Template Engine,Custom filter]
- [structure.md,Structure,Basic]
- [structure/controller.md,Structure,Controller]
- [structure/models.md,Structure,Model]
- [structure/route.md,Structure,Route]
- [structure/Extends.md,Structure,Extends]
- [structure/template_engine.md,Structure,View]
- [structure/feature_config.md,Structure,Config]
- [utilities.md,Utilities,Basic]
- [utilities/logger.md,Utilities,Logger]
- [utilities/flash_message.md,Utilities,Flash messages]
- [utilities/global_function.md,Utilities,Global functions and Variable]


theme: readthedocs
